/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "r14.4.0/36413-e40.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-example`
 */

#ifndef	_AdditionalCSFallbackIndicator_H_
#define	_AdditionalCSFallbackIndicator_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum AdditionalCSFallbackIndicator {
	AdditionalCSFallbackIndicator_no_restriction	= 0,
	AdditionalCSFallbackIndicator_restriction	= 1
	/*
	 * Enumeration is extensible
	 */
} e_AdditionalCSFallbackIndicator;

/* AdditionalCSFallbackIndicator */
typedef long	 AdditionalCSFallbackIndicator_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AdditionalCSFallbackIndicator;
asn_struct_free_f AdditionalCSFallbackIndicator_free;
asn_struct_print_f AdditionalCSFallbackIndicator_print;
asn_constr_check_f AdditionalCSFallbackIndicator_constraint;
ber_type_decoder_f AdditionalCSFallbackIndicator_decode_ber;
der_type_encoder_f AdditionalCSFallbackIndicator_encode_der;
xer_type_decoder_f AdditionalCSFallbackIndicator_decode_xer;
xer_type_encoder_f AdditionalCSFallbackIndicator_encode_xer;
oer_type_decoder_f AdditionalCSFallbackIndicator_decode_oer;
oer_type_encoder_f AdditionalCSFallbackIndicator_encode_oer;
per_type_decoder_f AdditionalCSFallbackIndicator_decode_uper;
per_type_encoder_f AdditionalCSFallbackIndicator_encode_uper;
per_type_decoder_f AdditionalCSFallbackIndicator_decode_aper;
per_type_encoder_f AdditionalCSFallbackIndicator_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _AdditionalCSFallbackIndicator_H_ */
#include <asn_internal.h>
