/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "r14.4.0/36413-e40.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-example`
 */

#ifndef	_Cdma2000OneXSRVCCInfo_H_
#define	_Cdma2000OneXSRVCCInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Cdma2000OneXMEID.h"
#include "Cdma2000OneXMSI.h"
#include "Cdma2000OneXPilot.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolExtensionContainer;

/* Cdma2000OneXSRVCCInfo */
typedef struct Cdma2000OneXSRVCCInfo {
	Cdma2000OneXMEID_t	 cdma2000OneXMEID;
	Cdma2000OneXMSI_t	 cdma2000OneXMSI;
	Cdma2000OneXPilot_t	 cdma2000OneXPilot;
	struct ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Cdma2000OneXSRVCCInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Cdma2000OneXSRVCCInfo;

#ifdef __cplusplus
}
#endif

#endif	/* _Cdma2000OneXSRVCCInfo_H_ */
#include <asn_internal.h>
