/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-PDU-Contents"
 * 	found in "r14.4.0/36413-e40.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-example`
 */

#ifndef	_E_RABFailedToSetupItemHOReqAck_H_
#define	_E_RABFailedToSetupItemHOReqAck_H_


#include <asn_application.h>

/* Including external dependencies */
#include "E-RAB-ID.h"
#include "Cause.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolExtensionContainer;

/* E-RABFailedToSetupItemHOReqAck */
typedef struct E_RABFailedToSetupItemHOReqAck {
	E_RAB_ID_t	 e_RAB_ID;
	Cause_t	 cause;
	struct ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E_RABFailedToSetupItemHOReqAck_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_E_RABFailedToSetupItemHOReqAck;

#ifdef __cplusplus
}
#endif

#endif	/* _E_RABFailedToSetupItemHOReqAck_H_ */
#include <asn_internal.h>
