/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-PDU-Contents"
 * 	found in "r14.4.0/36413-e40.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-example`
 */

#ifndef	_E_RABModifyListBearerModRes_H_
#define	_E_RABModifyListBearerModRes_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolIE_SingleContainer;

/* E-RABModifyListBearerModRes */
typedef struct E_RABModifyListBearerModRes {
	A_SEQUENCE_OF(struct ProtocolIE_SingleContainer) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E_RABModifyListBearerModRes_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_E_RABModifyListBearerModRes;

#ifdef __cplusplus
}
#endif

#endif	/* _E_RABModifyListBearerModRes_H_ */
#include <asn_internal.h>
