/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "r14.4.0/36413-e40.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-example`
 */

#ifndef	_GUMMEIList_H_
#define	_GUMMEIList_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct GUMMEI;

/* GUMMEIList */
typedef struct GUMMEIList {
	A_SEQUENCE_OF(struct GUMMEI) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GUMMEIList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GUMMEIList;

#ifdef __cplusplus
}
#endif

#endif	/* _GUMMEIList_H_ */
#include <asn_internal.h>
