/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "r14.4.0/36413-e40.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-example`
 */

#include "ImmediateMDT.h"

#include "M1ThresholdEventA2.h"
#include "M1PeriodicReporting.h"
#include "ProtocolExtensionContainer.h"
asn_TYPE_member_t asn_MBR_ImmediateMDT_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ImmediateMDT, measurementsToActivate),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MeasurementsToActivate,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"measurementsToActivate"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ImmediateMDT, m1reportingTrigger),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_M1ReportingTrigger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"m1reportingTrigger"
		},
	{ ATF_POINTER, 3, offsetof(struct ImmediateMDT, m1thresholdeventA2),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_M1ThresholdEventA2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"m1thresholdeventA2"
		},
	{ ATF_POINTER, 2, offsetof(struct ImmediateMDT, m1periodicReporting),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_M1PeriodicReporting,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"m1periodicReporting"
		},
	{ ATF_POINTER, 1, offsetof(struct ImmediateMDT, iE_Extensions),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ProtocolExtensionContainer_6602P60,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iE-Extensions"
		},
};
static const int asn_MAP_ImmediateMDT_oms_1[] = { 2, 3, 4 };
static const ber_tlv_tag_t asn_DEF_ImmediateMDT_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ImmediateMDT_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* measurementsToActivate */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* m1reportingTrigger */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* m1thresholdeventA2 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* m1periodicReporting */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* iE-Extensions */
};
asn_SEQUENCE_specifics_t asn_SPC_ImmediateMDT_specs_1 = {
	sizeof(struct ImmediateMDT),
	offsetof(struct ImmediateMDT, _asn_ctx),
	asn_MAP_ImmediateMDT_tag2el_1,
	5,	/* Count of tags in the map */
	asn_MAP_ImmediateMDT_oms_1,	/* Optional members */
	3, 0,	/* Root/Additions */
	5,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ImmediateMDT = {
	"ImmediateMDT",
	"ImmediateMDT",
	&asn_OP_SEQUENCE,
	asn_DEF_ImmediateMDT_tags_1,
	sizeof(asn_DEF_ImmediateMDT_tags_1)
		/sizeof(asn_DEF_ImmediateMDT_tags_1[0]), /* 1 */
	asn_DEF_ImmediateMDT_tags_1,	/* Same as above */
	sizeof(asn_DEF_ImmediateMDT_tags_1)
		/sizeof(asn_DEF_ImmediateMDT_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ImmediateMDT_1,
	5,	/* Elements count */
	&asn_SPC_ImmediateMDT_specs_1	/* Additional specs */
};

