/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "r14.4.0/36413-e40.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-example`
 */

#include "RLFReportInformation.h"

#include "ProtocolExtensionContainer.h"
asn_TYPE_member_t asn_MBR_RLFReportInformation_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RLFReportInformation, uE_RLF_Report_Container),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UE_RLF_Report_Container,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"uE-RLF-Report-Container"
		},
	{ ATF_POINTER, 2, offsetof(struct RLFReportInformation, uE_RLF_Report_Container_for_extended_bands),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UE_RLF_Report_Container_for_extended_bands,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"uE-RLF-Report-Container-for-extended-bands"
		},
	{ ATF_POINTER, 1, offsetof(struct RLFReportInformation, iE_Extensions),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ProtocolExtensionContainer_6602P86,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iE-Extensions"
		},
};
static const int asn_MAP_RLFReportInformation_oms_1[] = { 1, 2 };
static const ber_tlv_tag_t asn_DEF_RLFReportInformation_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_RLFReportInformation_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* uE-RLF-Report-Container */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* uE-RLF-Report-Container-for-extended-bands */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* iE-Extensions */
};
asn_SEQUENCE_specifics_t asn_SPC_RLFReportInformation_specs_1 = {
	sizeof(struct RLFReportInformation),
	offsetof(struct RLFReportInformation, _asn_ctx),
	asn_MAP_RLFReportInformation_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_RLFReportInformation_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	3,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_RLFReportInformation = {
	"RLFReportInformation",
	"RLFReportInformation",
	&asn_OP_SEQUENCE,
	asn_DEF_RLFReportInformation_tags_1,
	sizeof(asn_DEF_RLFReportInformation_tags_1)
		/sizeof(asn_DEF_RLFReportInformation_tags_1[0]), /* 1 */
	asn_DEF_RLFReportInformation_tags_1,	/* Same as above */
	sizeof(asn_DEF_RLFReportInformation_tags_1)
		/sizeof(asn_DEF_RLFReportInformation_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_RLFReportInformation_1,
	3,	/* Elements count */
	&asn_SPC_RLFReportInformation_specs_1	/* Additional specs */
};

