/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "r14.4.0/36413-e40.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-example`
 */

#ifndef	_SONInformationReport_H_
#define	_SONInformationReport_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SONInformationReport_PR {
	SONInformationReport_PR_NOTHING,	/* No components present */
	SONInformationReport_PR_rLFReportInformation
	/* Extensions may appear below */
	
} SONInformationReport_PR;

/* Forward declarations */
struct RLFReportInformation;

/* SONInformationReport */
typedef struct SONInformationReport {
	SONInformationReport_PR present;
	union SONInformationReport_u {
		struct RLFReportInformation	*rLFReportInformation;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SONInformationReport_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SONInformationReport;

#ifdef __cplusplus
}
#endif

#endif	/* _SONInformationReport_H_ */
#include <asn_internal.h>
