/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "r14.4.0/36413-e40.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-example`
 */

#include "SONInformation.h"

#include "SONInformationReply.h"
#include "SONInformation-Extension.h"
static asn_oer_constraints_t asn_OER_type_SONInformation_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_SONInformation_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  1,  1,  0,  1 }	/* (0..1,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_SONInformation_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SONInformation, choice.sONInformationRequest),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SONInformationRequest,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"sONInformationRequest"
		},
	{ ATF_POINTER, 0, offsetof(struct SONInformation, choice.sONInformationReply),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SONInformationReply,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"sONInformationReply"
		},
	{ ATF_POINTER, 0, offsetof(struct SONInformation, choice.sONInformation_Extension),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SONInformation_Extension,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"sONInformation-Extension"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_SONInformation_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* sONInformationRequest */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* sONInformationReply */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* sONInformation-Extension */
};
asn_CHOICE_specifics_t asn_SPC_SONInformation_specs_1 = {
	sizeof(struct SONInformation),
	offsetof(struct SONInformation, _asn_ctx),
	offsetof(struct SONInformation, present),
	sizeof(((struct SONInformation *)0)->present),
	asn_MAP_SONInformation_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0,
	2	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_SONInformation = {
	"SONInformation",
	"SONInformation",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_SONInformation_constr_1, &asn_PER_type_SONInformation_constr_1, CHOICE_constraint },
	asn_MBR_SONInformation_1,
	3,	/* Elements count */
	&asn_SPC_SONInformation_specs_1	/* Additional specs */
};

