/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "r14.4.0/36413-e40.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-example`
 */

#ifndef	_TransportInformation_H_
#define	_TransportInformation_H_


#include <asn_application.h>

/* Including external dependencies */
#include "TransportLayerAddress.h"
#include "GTP-TEID.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* TransportInformation */
typedef struct TransportInformation {
	TransportLayerAddress_t	 transportLayerAddress;
	GTP_TEID_t	 uL_GTP_TEID;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TransportInformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TransportInformation;

#ifdef __cplusplus
}
#endif

#endif	/* _TransportInformation_H_ */
#include <asn_internal.h>
