/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "r14.4.0/36413-e40.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-example`
 */

#ifndef	_UE_S1AP_IDs_H_
#define	_UE_S1AP_IDs_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MME-UE-S1AP-ID.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum UE_S1AP_IDs_PR {
	UE_S1AP_IDs_PR_NOTHING,	/* No components present */
	UE_S1AP_IDs_PR_uE_S1AP_ID_pair,
	UE_S1AP_IDs_PR_mME_UE_S1AP_ID
	/* Extensions may appear below */
	
} UE_S1AP_IDs_PR;

/* Forward declarations */
struct UE_S1AP_ID_pair;

/* UE-S1AP-IDs */
typedef struct UE_S1AP_IDs {
	UE_S1AP_IDs_PR present;
	union UE_S1AP_IDs_u {
		struct UE_S1AP_ID_pair	*uE_S1AP_ID_pair;
		MME_UE_S1AP_ID_t	 mME_UE_S1AP_ID;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UE_S1AP_IDs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UE_S1AP_IDs;

#ifdef __cplusplus
}
#endif

#endif	/* _UE_S1AP_IDs_H_ */
#include <asn_internal.h>
