/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "r14.4.0/36413-e40.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-example`
 */

#include "UEAggregateMaximumBitrate.h"

#include "ProtocolExtensionContainer.h"
static asn_TYPE_member_t asn_MBR_UEAggregateMaximumBitrate_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct UEAggregateMaximumBitrate, uEaggregateMaximumBitRateDL),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BitRate,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"uEaggregateMaximumBitRateDL"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct UEAggregateMaximumBitrate, uEaggregateMaximumBitRateUL),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BitRate,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"uEaggregateMaximumBitRateUL"
		},
	{ ATF_POINTER, 1, offsetof(struct UEAggregateMaximumBitrate, iE_Extensions),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ProtocolExtensionContainer_6602P109,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iE-Extensions"
		},
};
static const int asn_MAP_UEAggregateMaximumBitrate_oms_1[] = { 2 };
static const ber_tlv_tag_t asn_DEF_UEAggregateMaximumBitrate_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_UEAggregateMaximumBitrate_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* uEaggregateMaximumBitRateDL */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* uEaggregateMaximumBitRateUL */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* iE-Extensions */
};
static asn_SEQUENCE_specifics_t asn_SPC_UEAggregateMaximumBitrate_specs_1 = {
	sizeof(struct UEAggregateMaximumBitrate),
	offsetof(struct UEAggregateMaximumBitrate, _asn_ctx),
	asn_MAP_UEAggregateMaximumBitrate_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_UEAggregateMaximumBitrate_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	3,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_UEAggregateMaximumBitrate = {
	"UEAggregateMaximumBitrate",
	"UEAggregateMaximumBitrate",
	&asn_OP_SEQUENCE,
	asn_DEF_UEAggregateMaximumBitrate_tags_1,
	sizeof(asn_DEF_UEAggregateMaximumBitrate_tags_1)
		/sizeof(asn_DEF_UEAggregateMaximumBitrate_tags_1[0]), /* 1 */
	asn_DEF_UEAggregateMaximumBitrate_tags_1,	/* Same as above */
	sizeof(asn_DEF_UEAggregateMaximumBitrate_tags_1)
		/sizeof(asn_DEF_UEAggregateMaximumBitrate_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_UEAggregateMaximumBitrate_1,
	3,	/* Elements count */
	&asn_SPC_UEAggregateMaximumBitrate_specs_1	/* Additional specs */
};

