/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "r14.4.0/36413-e40.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-example`
 */

#ifndef	_WarningAreaList_H_
#define	_WarningAreaList_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum WarningAreaList_PR {
	WarningAreaList_PR_NOTHING,	/* No components present */
	WarningAreaList_PR_cellIDList,
	WarningAreaList_PR_trackingAreaListforWarning,
	WarningAreaList_PR_emergencyAreaIDList
	/* Extensions may appear below */
	
} WarningAreaList_PR;

/* Forward declarations */
struct ECGIList;
struct TAIListforWarning;
struct EmergencyAreaIDList;

/* WarningAreaList */
typedef struct WarningAreaList {
	WarningAreaList_PR present;
	union WarningAreaList_u {
		struct ECGIList	*cellIDList;
		struct TAIListforWarning	*trackingAreaListforWarning;
		struct EmergencyAreaIDList	*emergencyAreaIDList;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} WarningAreaList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_WarningAreaList;

#ifdef __cplusplus
}
#endif

#endif	/* _WarningAreaList_H_ */
#include <asn_internal.h>
